name: Automated Releases

on:
  release:
    types: [published, edited]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_dir: everyone.dance-linux-x64
            artifact_name: everyone.dance-linux-x64.zip
            asset_name: Linux Release
          - os: windows-latest
            artifact_dir: everyone.dance-win32-x64
            artifact_name: everyone.dance-win32-x64.zip
            asset_name: Windows Release
          - os: macos-latest
            artifact_dir: everyone.dance-darwin-x64
            artifact_name: everyone.dance-macos-x64.zip
            asset_name: Mac Release

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run bundle
    - run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              npm run make-linux
         elif [ "$RUNNER_OS" == "Windows" ]; then
              npm run make
         else
              npm run make-mac
         fi
    - if: ${{ matrix.os }} == "macos-latest"
      run: zip -r ${{ matrix.artifact_name }} out/${{ matrix.artifact_dir }}
    - if: ${{ matrix.os }} == "ubuntu-latest"
      uses: montudor/action-zip@v0.1.1
      with:
        args: zip -qq -r ${{ matrix.artifact_name }} out/${{ matrix.artifact_dir }}
    - if: ${{ matrix.os }} == "windows-latest"
      run: powershell Compress-Archive out/${{ matrix.artifact_dir }} ${{ matrix.artifact_name }}
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}