name: Automated Releases

on:
  release:
    types: [published, created, edited]

jobs:
  release-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run bundle
    - run: npm run make-linux
      
#   release-macos:

#     runs-on: macos-latest

#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x, 15.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm run bundle
#     - run: npm run make
#     - run: npm test
      
#   release-windows:

#     runs-on: windows-latest

#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x, 15.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm run bundle
#     - run: npm run make
#     - run: npm test
