name: Automated Releases

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - name: get-npm-version
            id: package-version
            uses: martinbeentjes/npm-get-version-action@master
          - os: ubuntu-latest
            artifact_dir: everyone.dance-linux-x64
            artifact_name: everyone.dance-linux-x64.zip
            asset_name: everyone.dance-linux-x64.zip
          - os: windows-latest
            artifact_dir: everyone.dance-win32-x64
            artifact_name: everyone.dance-win32-x64.zip
            asset_name: everyone.dance-win32-x64.zip
          - os: macos-latest
            artifact_dir: everyone.dance-darwin-x64
            artifact_name: everyone.dance-macos-x64.zip
            asset_name: everyone.dance-macos-x64.zip

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run bundle
    - if: runner.os == 'macOS'
      run: npm run make-mac
    - if: runner.os == 'macOS'
      run: zip -r -y ${{ matrix.artifact_name }} out/${{ matrix.artifact_dir }}
    - if: runner.os == 'Linux'
      run: npm run make-linux
    - if: runner.os == 'Linux'
      uses: papeloto/action-zip@v1
      with:
        files: out/${{ matrix.artifact_dir }}/
        dest: ${{ matrix.artifact_name }}
    - if: runner.os == 'Windows'
      run: npm run make
    - if: runner.os == 'Windows'
      run: powershell Compress-Archive out/${{ matrix.artifact_dir }} ${{ matrix.artifact_name }}
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
